### ISSUE TITLE
Thau backend seems to try creating dataschema_versions table on every startup

### ISSUE THREAD

**Issue by mauquoic** [MGrin/thau#42]
If docker-compose up is run for the first time with a postgres db, the schemas are correctly created. However, after shutting down all containers and running them again, the following error is shown:
db_1      | 2020-06-07 07:54:48.736 UTC [32] ERROR:  relation "thau_dataschema_versions" already exists
db_1      | 2020-06-07 07:54:48.736 UTC [32] STATEMENT:
db_1      |         CREATE TABLE THAU_DATASCHEMA_VERSIONS (
db_1      |           id SERIAL primary key,
db_1      |           step TEXT not null,
db_1      |           timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
db_1      |         );
db_1      |
thau_1    | error: relation "thau_dataschema_versions" already exists
thau_1    |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:581:48)
thau_1    |     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:380:19)
thau_1    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:116:22)
thau_1    |     at Socket.emit (events.js:315:20)
thau_1    |     at addChunk (_stream_readable.js:302:12)
thau_1    |     at readableAddChunk (_stream_readable.js:278:9)
thau_1    |     at Socket.Readable.push (_stream_readable.js:217:10)
thau_1    |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
thau_1    |   length: 118,
thau_1    |   severity: 'ERROR',
thau_1    |   code: '42P07',
thau_1    |   detail: undefined,
thau_1    |   hint: undefined,
thau_1    |   position: undefined,
thau_1    |   internalPosition: undefined,
thau_1    |   internalQuery: undefined,
thau_1    |   where: undefined,
thau_1    |   schema: undefined,
thau_1    |   table: undefined,
thau_1    |   column: undefined,
thau_1    |   dataType: undefined,
thau_1    |   constraint: undefined,
thau_1    |   file: 'heap.c',
thau_1    |   line: '1155',
thau_1    |   routine: 'heap_create_with_catalog'
thau_1    | }

**Comment by mauquoic** [comment]
If only the table thau_dataschema_versions is deleted before a new startup, the same error occurs with table users. Hence, all thau tables must be removed before every startup.

**Comment by MGrin** [comment]
Thanks! This is the bug in Thau for sure, it's related to the wrong syncronization if the current state of the DB with the Thau codee itself. Fix is coming in a couple of hours
